languageCode = "en"
languageName = "English"
weight = 1
title = "bbnoir's blog"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  description = "bbnoir's blog"
  copyright = "Copy, _right?_ "

[author]
  name = "bbnoir"
  image = "img/logo.png"
  bio = "programmer - gamer - filmlover"
  headline = "I'm only human"
  links = [
    # { email = "bbnoir83@gmail.com" },
    { x-twitter = "https://twitter.com/bbnoir83" },
    { github = "https://github.com/bbnoir" },
    { youtube = "https://www.youtube.com/@bbnoir-ty9cj" },
    # { link = "https://link-to-some-website.com/" },
    # { linkedin = "https://linkedin.com/in/username" },
    # { medium = "https://medium.com/username" },
  ]
